### ISSUE TITLE
Difference between branches

### ISSUE THREAD

**Issue by ttodua** [tarecord/sign-in-with-google#97]
Can you explain the difference between branches?  `develop` branch is set as main, so is `master` obsolete branch we should ignore?

**Comment by tarecord** [comment]
Hey @ttodua, great question. The `develop` branch is where all features are created and merged. The `master` branch is where the source code always reflects a production-ready state, which is why `develop` is the default branch.

You can read more about this workflow here: https://nvie.com/posts/a-successful-git-branching-model/
